export const allProducts = [
    {
        category: '1',
        name: '經典豆沙包',
        price: 35,
        slogan: '入口綿密的豆沙，點心界經典中的經典',
        image: 1,
        label: '人氣NO.1',
        link: '#',

    },
    {
        category: '1',
        name: '牛奶芋泥包',
        price: 35,
        slogan: '香氣四溢的芋頭味，大人小孩的最愛',
        image: 2,
        label: '',
        link: '#',

    },
    // {
    //     category: '1',
    //     name: '芝麻豆沙包',
    //     price: 35,
    //     slogan: '入口綿密的豆沙，點心界經典中的經典',
    //     image: 3,
    //     label: '人氣NO.1',
    // },
    {
        category: '1',
        name: '黑糖芝麻包',
        price: 35,
        slogan: '濃郁爆醬的黑芝麻餡，讓你一口成為老饕',
        image: 4,
        label: '人氣NO.3',
        link: '#',

    },
    {
        category: '1',
        name: '芝麻花生包',
        price: 35,
        slogan: '小豆包子獨家口味，長年銷售亞軍',
        image: 5,
        label: '人氣NO.2',
        link: '#',

    },
    // {
    //     category: '1',
    //     name: '濃郁芝麻包',
    //     price: 35,
    //     slogan: '入口綿密的豆沙，點心界經典中的經典',
    //     image: 6,
    //     label: '人氣NO.1',
    // },
    {
        category: '1',
        name: '松露巧克力包',
        price: 35,
        slogan: '高雅的松露巧克力，不是情人節也可以吃喔',
        image: 7,
        label: '新口味',
        link: '#',

    },
    {
        category: '1',
        name: '胚芽起司包',
        price: 35,
        slogan: '外表看似單調，內涵卻很性感暴露',
        image: 8,
        label: '',
        link: '#',

    },
    {
        category: '2',
        name: '飽足鮮肉包',
        price: 35,
        slogan: '想吃肉是吧？給你超多肉，超飽足',
        image: 9,
        label: '肉食族',
        link: '#',

    },
    {
        category: '2',
        name: '香菇滷肉包',
        price: 35,
        slogan: '和滷肉飯的滷肉有點像，老闆貼心幫你加幾多香菇',
        image: 10,
        label: '',
        link: '#',

    },
    {
        category: '2',
        name: '雪菜鮮肉包',
        price: 35,
        slogan: '想吃肉又想吃菜，那就來顆雪菜鮮肉包',
        image: 11,
        label: '',
        link: '#',

    },
    {
        category: '2',
        name: '咖哩鮮肉包',
        price: 35,
        slogan: '鮮肉包口味太淡？老闆幫你加咖哩粉在麵團裡了',
        image: 12,
        label: '新口味',
        link: '#',

    },
    // {
    //     category: '2',
    //     name: '港式叉燒包',
    //     price: 35,
    //     slogan: '入口綿密的豆沙，點心界經典中的經典',
    //     image: 13,
    //     label: '',
    // },
    {
        category: '2',
        name: '酸菜獅子頭包',
        price: 40,
        slogan: '吃起來像掛包口感，有古早味的味道',
        image: 14,
        label: '',
        link: '#',

    },
    {
        category: '2',
        name: '素高麗菜包',
        price: 40,
        slogan: '趕快來一顆高麗菜包，一餐補足蔬菜量',
        image: 15,
        label: '蔬菜多多',
        link: '#',

    },
    // {
    //     category: '2',
    //     name: '葷高麗菜包',
    //     price: 40,
    //     slogan: '入口綿密的豆沙，點心界經典中的經典',
    //     image: 16,
    //     label: '蔬菜多多',
    // },
    {
        category: '3',
        name: '黑糖饅頭',
        price: 30,
        slogan: '不知道早餐要吃啥，就吃個還不錯的黑糖饅頭吧',
        image: 17,
        label: '',
        link: '#',

    },
    {
        category: '3',
        name: '五股無糖饅頭',
        price: 40,
        slogan: '減肥第一天吃的早餐，比你想像中好吃',
        image: 18,
        label: '',
        link: '#',

    },
    {
        category: '3',
        name: '紅麴養生饅頭',
        price: 40,
        slogan: '紅麴是什麼？能吃嗎？好吃嗎？吃了就知道',
        image: 19,
        label: '媽媽最愛',
        link: '#',

    },
    {
        category: '3',
        name: '南瓜饅頭',
        price: 40,
        slogan: '是南瓜，不是麻瓜，吃了不會變麻瓜的南瓜饅頭',
        image: 20,
        label: '南瓜族',
        link: '#',

    },
    {
        category: '3',
        name: '地瓜饅頭',
        price: 40,
        slogan: '是在吃地瓜，還是在吃饅頭，傻傻分不清楚',
        image: 21,
        label: '養生推薦',
        link: '#',

    },
    {
        category: '3',
        name: '芝麻豆沙饅頭',
        price: 40,
        slogan: '芝麻配紅豆，點心界中的最佳男女主角',
        image: 22,
        label: '',
        link: '#',

    },
    {
        category: '4',
        name: '爆醬起司饅頭',
        price: 40,
        slogan: '兩片起司都包在饅頭裡了，爆醬吧',
        image: 23,
        label: '早餐適合',
        link: '#',

    },
    {
        category: '4',
        name: '紫米多多饅頭',
        price: 40,
        slogan: '就是要吃紫米，紫米多多ＱＱ饅頭',
        image: 24,
        label: '老闆最愛',
        link: '#',

    },
    {
        category: '4',
        name: '五穀香腸饅頭',
        price: 40,
        slogan: '融入養生五穀的麵團，德式香腸，中西融合',
        image: 25,
        label: '',
        link: '#',

    },
    {
        category: '4',
        name: '芋頭奶油饅頭',
        price: 40,
        slogan: '香氣四溢的芋頭味，配上有點罪惡感的天然奶油',
        image: 26,
        label: '罪惡點心',
        link: '#',
    },
    {
        category: '4',
        name: '芋頭地瓜饅頭',
        price: 40,
        slogan: '香氣四溢的芋頭味，整塊綿密的地瓜',
        image: 28,
        label: '早餐適合',
        link: 'products-28.html',
    },
]